import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { mkdir, mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const require=createRequire(process.env.PLAYWRIGHT_MODULE_ROOT?join(process.env.PLAYWRIGHT_MODULE_ROOT,'package.json'):import.meta.url);
const {chromium}=require('playwright');
const base=process.env.TEST_URL||'http://localhost:4173';
const output=new URL('../test-results/',import.meta.url);await mkdir(output,{recursive:true});
const profile=await mkdtemp(join(tmpdir(),'health-diary-demo-test-'));
const errors=[],external=[];
let context;
const pass=message=>console.log('PASS '+message);
try {
  context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:390,height:844},acceptDownloads:true});
  context.on('request',request=>{if(new URL(request.url()).origin!==new URL(base).origin)external.push(request.url());});
  const page=context.pages()[0];
  page.on('pageerror',error=>errors.push(error.message));
  page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
  await page.goto(base);
  await page.getByText('Ready offline',{exact:true}).waitFor();
  await page.waitForFunction(()=>!document.getElementById('demo-start').disabled&&!!navigator.serviceWorker.controller);
  assert.match(await page.locator('#notes').inputValue(),/FICTIONAL SAMPLE/);
  assert.equal(await page.locator('#import-backup').isDisabled(),true);
  assert.equal(await page.locator('#prescription-files').isDisabled(),true);
  pass('Demo starts with fictional records; real file and backup imports disabled');
  for(const width of [320,390,768,1440]) {
    await page.setViewportSize({width,height:900});
    await page.locator('#demo-start').click();
    for(let step=1;step<=6;step++) {
      await page.getByText(`QUICK TOUR · ${step} OF 6`,{exact:true}).waitFor();
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`No overflow at ${width}, step ${step}`);
      if(width===390&&step===1)await page.screenshot({path:fileURLToPath(new URL('demo-mobile-tour.png',output)),fullPage:true});
      await page.locator('#demo-next').click();
    }
    await page.locator('#demo-tour').waitFor({state:'hidden'});
  }
  await page.setViewportSize({width:390,height:844});
  await page.locator('#demo-start').click();await page.locator('#demo-next').click();await page.locator('#demo-back').click();
  await page.getByText('QUICK TOUR · 1 OF 6',{exact:true}).waitFor();
  await page.keyboard.press('Escape');assert.equal(await page.locator('#demo-tour').isVisible(),false);
  const tip=page.getByRole('button',{name:'How notes save'});
  await tip.focus();await page.keyboard.press('Enter');assert.equal(await tip.getAttribute('aria-expanded'),'true');
  await page.keyboard.press('Escape');assert.equal(await tip.getAttribute('aria-expanded'),'false');
  pass('Tour, Back, Finish, Escape and keyboard tips work at 320–1440 px');
  const original=await page.locator('#notes').inputValue();
  await page.locator('#notes').fill('FICTIONAL TEST EDIT: a sample walk.');
  await page.getByText('Saved for this demo ✓',{exact:true}).waitFor();
  await page.locator('#save-entry').click();assert.equal(await page.locator('#notes').isVisible(),false);
  await page.getByRole('link',{name:'Past entries',exact:true}).click();
  await page.getByText('4 entries',{exact:true}).waitFor();
  await page.locator('#search').fill('headache');await page.getByText('1 entry found',{exact:true}).waitFor();
  await page.locator('#search').fill('FICTIONAL TEST EDIT');await page.getByText('1 entry found',{exact:true}).waitFor();
  await page.getByRole('link',{name:'Doctor visit',exact:true}).click();
  await page.locator('#visits-list').getByRole('heading',{name:'Dr. Taylor — fictional example',exact:true}).waitFor();
  await page.getByRole('button',{name:'View DEMO-only-sample.png',exact:true}).click();
  await page.locator('#prescription-image').waitFor({state:'visible'});
  assert.equal(await page.locator('#prescription-image').evaluate(img=>img.naturalWidth),1000);
  await page.screenshot({path:fileURLToPath(new URL('demo-attachment.png',output)),fullPage:true});
  await page.getByRole('button',{name:'Close prescription',exact:true}).click();
  assert.match(await page.locator('#report-content').innerText(),/FICTIONAL TEST EDIT/);
  await page.getByRole('button',{name:'Edit visit with Dr. Taylor — fictional example',exact:true}).click();
  await page.locator('#visit-doctor').fill('Dr. Demo — edited sample');await page.locator('#visit-time').fill('11:15');await page.locator('#save-visit').click();
  await page.locator('#visits-list').getByRole('heading',{name:'Dr. Demo — edited sample',exact:true}).waitFor();
  const downloadEvent=page.waitForEvent('download');await page.locator('#download-report').click();
  const report=await downloadEvent;assert.match(await readFile(await report.path(),'utf8'),/FICTIONAL TEST EDIT/);
  const other=await context.newPage();await other.goto(base);await other.waitForFunction(()=>!document.getElementById('demo-start').disabled);
  assert.equal(await other.locator('#notes').inputValue(),original);await other.close();
  pass('Search, visit editing, sample image preview and report export work; tabs have separate samples');
  await page.locator('#theme-toggle').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  await page.reload();await page.waitForFunction(()=>!document.getElementById('demo-start').disabled);
  await page.getByRole('link',{name:'Write a note',exact:true}).click();await page.locator('#today-view').waitFor({state:'visible'});
  assert.equal(await page.locator('#notes').inputValue(),original);
  assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
  assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage)),['health-diary-theme']);
  assert.deepEqual(await page.evaluate(()=>indexedDB.databases()),[]);
  await page.locator('#notes').fill('FICTIONAL TEST RESET');await page.getByText('Saved for this demo ✓',{exact:true}).waitFor();
  page.once('dialog',dialog=>dialog.accept());await page.locator('#demo-reset').click();await page.waitForFunction(()=>!document.getElementById('demo-start').disabled);
  assert.equal(await page.locator('#notes').inputValue(),original);
  await context.setOffline(true);await page.reload();await page.waitForFunction(()=>!document.getElementById('demo-start').disabled);
  await page.getByText('Offline · you can keep writing',{exact:true}).waitFor();
  await page.locator('#demo-start').click();await page.getByText('QUICK TOUR · 1 OF 6',{exact:true}).waitFor();await page.locator('#demo-exit').click();
  await page.getByRole('link',{name:'Doctor visit',exact:true}).click();await page.getByRole('button',{name:'View DEMO-only-sample.png',exact:true}).click();await page.locator('#prescription-image').waitFor({state:'visible'});await page.locator('#close-prescription').click();
  await context.setOffline(false);await page.getByRole('link',{name:'Write a note',exact:true}).click();await page.locator('#theme-toggle').click();
  await page.screenshot({path:fileURLToPath(new URL('demo-mobile-dark.png',output)),fullPage:true});
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:fileURLToPath(new URL('demo-desktop-dark.png',output)),fullPage:true});
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  pass('Refresh/reset restores samples; only theme persists; offline tour and attachment work; no external requests or browser errors');
} finally { await context?.close();await rm(profile,{recursive:true,force:true}); }
