import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdir, readFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
const require = createRequire(process.env.PLAYWRIGHT_MODULE_ROOT ? join(process.env.PLAYWRIGHT_MODULE_ROOT,'package.json') : import.meta.url);
const { chromium } = require('playwright');
const base = process.env.TEST_URL || 'http://localhost:4173';
const output = new URL('../test-results/',import.meta.url);
await mkdir(output,{recursive:true});
const profile=await mkdtemp(join(tmpdir(),'health-diary-test-'));
let context;
const errors=[], externalRequests=[];
async function launch() {
  context=await chromium.launchPersistentContext(profile,{channel:'chrome',headless:true,viewport:{width:390,height:844},deviceScaleFactor:1,acceptDownloads:true});
  context.on('page',page=>page.on('pageerror',error=>errors.push(error.message)));
  context.on('request',request=>{if(new URL(request.url()).origin!==new URL(base).origin)externalRequests.push(request.url());});
  return context;
}
const check = message => console.log(`PASS ${message}`);
try {
  await launch();
  let page=context.pages()[0];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(base);
  await page.getByText('Ready offline',{exact:true}).waitFor();
  await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
  const today=await page.locator('#entry-date').inputValue();
  assert.equal(await page.locator('#notes').inputValue(),'');
  check('Empty diary, app manifest, and offline shell ready');
  const manifest=await (await context.request.get(base+'/manifest.webmanifest')).json();
  assert.equal(manifest.display,'standalone');
  for(const icon of manifest.icons)assert.equal((await context.request.get(base+icon.src)).status(),200);
  for(const width of [320,390,768,1440]){
    await page.setViewportSize({width,height:900});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Overflow at ${width}px`);
  }
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:fileURLToPath(new URL('mobile.png',output)),fullPage:true});
  check('Responsive layout at 320, 390, 768, and 1440 pixels');
  const note='09:00 — Felt tired after breakfast. Rest helped.\nLiteral text: <img src=x onerror=alert(1)>';
  await page.locator('#notes').fill(note);
  await page.locator('[data-mood="3"]').click();
  await page.locator('#extra-details summary').click();
  await page.locator('#symptoms').fill('Headache at 10:00; lasted 30 minutes.');
  await page.locator('#medicines').fill('Recorded medicine name and dose.');
  await page.locator('#questions').fill('Could we discuss the recurring tiredness?');
  await page.getByText('Saved on this device ✓',{exact:true}).waitFor();
  await page.reload();
  await page.getByText('Saved on this device ✓',{exact:true}).waitFor();
  assert.equal(await page.locator('#notes').inputValue(),note);
  assert.equal(await page.locator('#questions').inputValue(),'Could we discuss the recurring tiredness?');
  assert.equal(await page.locator('[data-mood="3"]').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#notes').isVisible(),false);
  check('Autosave and all entry fields survive reload');
  await context.setOffline(true);
  await page.reload();
  await page.getByText(/^(Offline · you can keep writing|Ready offline)$/).waitFor();
  assert.equal(await page.evaluate(()=>fetch('/network-probe',{cache:'no-store'}).then(()=>false,()=>true)),true);
  await page.locator('#notes-details summary').click();
  await page.locator('#notes').fill(note+'\nOffline note at 16:00.');
  await page.getByText('Saved on this device ✓',{exact:true}).waitFor();
  await context.close();
  await launch();
  await context.setOffline(true);
  page=context.pages()[0];
  await page.goto(base);
  await page.getByText(/^(Offline · you can keep writing|Ready offline)$/).waitFor();
  assert.equal(await page.evaluate(()=>fetch('/network-probe',{cache:'no-store'}).then(()=>false,()=>true)),true);
  assert.equal(await page.locator('#notes').inputValue(),note+'\nOffline note at 16:00.');
  check('Offline writing and offline reopen after browser restart');
  const previousDate=new Date(today+'T12:00:00');previousDate.setDate(previousDate.getDate()-1);
  const yesterday=`${previousDate.getFullYear()}-${String(previousDate.getMonth()+1).padStart(2,'0')}-${String(previousDate.getDate()).padStart(2,'0')}`;
  await page.locator('#entry-date').fill(yesterday);
  await page.locator('#entry-date').dispatchEvent('change');
  await page.waitForFunction(()=>document.querySelector('#notes').value==='');
  await page.locator('#notes').fill('An earlier day, recorded later.');
  await page.getByText('Saved on this device ✓',{exact:true}).waitFor();
  await page.getByRole('link',{name:'Past entries',exact:true}).click();
  await page.locator('.entry-card').first().waitFor();
  assert.equal(await page.locator('.entry-card').count(),2);
  assert.equal(await page.locator('.entry-card img').count(),0);
  await page.locator('#search').fill('headache');
  await page.waitForFunction(()=>document.querySelectorAll('.entry-card').length===1);
  await page.locator('.entry-card').click();
  await page.locator('#today-view').waitFor({state:'visible'});
  assert.equal(await page.locator('#entry-date').inputValue(),today);
  check('Past-date entry, search, safe text rendering, and editing');
  await page.getByRole('link',{name:'Doctor visit',exact:true}).click();
  await page.locator('.report-entry').first().waitFor();
  assert.equal(await page.locator('.report-entry').count(),2);
  assert.ok((await page.locator('.question-section').innerText()).includes('recurring tiredness'));
  const reportDownload=page.waitForEvent('download');
  await page.locator('#download-report').click();
  const report=await reportDownload;
  const reportText=await readFile(await report.path(),'utf8');
  assert.ok(reportText.includes('Offline note at 16:00.'));
  assert.ok(reportText.includes('An earlier day'));
  await page.pdf({path:fileURLToPath(new URL('doctor-report.pdf',output)),format:'A4',printBackground:true});
  await page.locator('#report-from').fill('2099-01-01');await page.locator('#report-from').dispatchEvent('change');
  assert.equal(await page.locator('#print-report').isDisabled(),true);
  await page.locator('#report-from').fill(yesterday);await page.locator('#report-from').dispatchEvent('change');
  await page.getByRole('button',{name:'Print / Save PDF'}).waitFor();
  check('Doctor report, questions, text download, PDF, and invalid range');
  await page.locator('#settings-button').click();
  const backupDownload=page.waitForEvent('download');
  await page.locator('#export-backup').click();
  const backup=await backupDownload;
  const backupData=JSON.parse(await readFile(await backup.path(),'utf8'));
  assert.equal(backupData.entries.length,2);
  await page.locator('#close-settings').click();
  await page.getByRole('link',{name:'Write a note',exact:true}).click();
  await page.locator('#delete-entry').click();
  await page.locator('#confirm-cancel').click();
  assert.ok((await page.locator('#notes').inputValue()).includes('Offline note'));
  await page.locator('#delete-entry').click();await page.locator('#confirm-ok').click();
  await page.waitForFunction(()=>document.querySelector('#notes').value==='');
  await page.locator('#settings-button').click();
  await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backupData))});
  await page.locator('#confirm-ok').click();
  await page.getByText('Backup restored.',{exact:true}).waitFor();
  await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"app":"invalid"}')});
  await page.getByText('This is not a supported Your Health Diary backup. Choose a backup downloaded from this app.',{exact:true}).waitFor();
  await page.locator('#close-settings').click();
  assert.ok((await page.locator('#notes').inputValue()).includes('Offline note'));
  check('Backup download, delete confirmation, restore, and invalid-file protection offline');
  // A stale writer must never overwrite an entry changed in another tab.
  const conflict=await page.evaluate(async date=>{
    const db=await import('/db.js'),entry=await db.getEntry(date);
    await db.putEntry({...entry,notes:'Newer entry',updatedAt:'2099-01-01T00:00:00.000Z'},entry.updatedAt);
    let rejected=false;
    try{await db.putEntry({...entry,notes:'Stale entry'},entry.updatedAt);}catch{rejected=true;}
    return {rejected,notes:(await db.getEntry(date)).notes};
  },today);
  assert.equal(conflict.rejected,true);assert.equal(conflict.notes,'Newer entry');
  check('Concurrent edits cannot silently overwrite newer notes');
  await context.setOffline(false);
  await page.setViewportSize({width:1440,height:1000});
  await page.reload();await page.getByText('Saved on this device ✓',{exact:true}).waitFor();
  await page.screenshot({path:fileURLToPath(new URL('desktop.png',output)),fullPage:true});
  assert.deepEqual(errors,[]);assert.deepEqual(externalRequests,[]);
  check('No browser errors or third-party requests');
  console.log('All diary smoke checks passed.');
}finally {await context?.close();await rm(profile,{recursive:true,force:true});}
